In [1]:
## imports

import numpy as np
import pandas as pd

from fastai.structured import *
from fastai.column_data import *
np.set_printoptions(threshold=50, edgeitems=20)
pd.set_option('display.max_columns', 100)
from lightgbm import LGBMClassifier
from datetime import datetime
from catboost import CatBoostClassifier, Pool, cv

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, roc_auc_score ,roc_curve,auc
from sklearn.model_selection import GridSearchCV,StratifiedKFold,KFold
from sklearn.preprocessing import LabelEncoder
seed = 45
#seed =145
% matplotlib inline
plt.style.use('fivethirtyeight')

In [3]:
### read data with some categorty name changes to raw files
PATH='F:/AV/WNS'
train_csv = 'train_catboost.csv'
test_csv = 'test_catboost.csv'
submit_csv = 'sample_submission_M0L0uXE.csv'

### read train, test and submission files
train = pd.read_csv(f'{PATH}/{train_csv}')
test = pd.read_csv(f'{PATH}/{test_csv}')
submission = pd.read_csv(f'{PATH}/{submit_csv}')

print("Shape of {}:{} {}:{} {}:{}".format('train',train.shape,'test',test.shape,'submission',submission.shape))

Shape of train:(54808, 14) test:(23490, 13) submission:(23490, 2)

In [4]:
### inspect data

train.head()

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,65438,Sales_Marketing,region_7,Masters_above,f,sourcing,1,35,5.0,8,1,0,49,0
1,65141,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,0,60,0
2,7513,Sales_Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,0,50,0
3,2542,Sales_Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,0,50,0
4,48945,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,0,73,0

In [5]:
### class balance

train['is_promoted'].value_counts()

## so approx 10% of past employees have been promoted

0    50140
1     4668
Name: is_promoted, dtype: int64

In [6]:
### lets check if there is any repeat in employees

len(train['employee_id'].unique()) == train.shape[0]

### so all IDs are unique

True

In [7]:
## null values

null_columns=train.columns[train.isnull().any()]
train[null_columns].isnull().sum()

## so 2 columns have null values

education               2409
previous_year_rating    4124
dtype: int64

In [8]:
### inspect null value columns
a = train[(train.education.isnull())]
_ = train[(train.education.isnull() | train.previous_year_rating.isnull())]

print(a.shape,_.shape)

(2409, 14) (6148, 14)

In [9]:
set(a.index).intersection(set(_.index)) == set(a.index)

### so everywhere where education is not present prev year rating is also not present, but vice-versa is not true

True

In [10]:
_.head(10)

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
10,29934,Technology,region_23,NaN,m,sourcing,1,30,NaN,1,0,0,77,0
21,33332,Operations,region_15,NaN,m,sourcing,1,41,4.0,11,0,0,57,0
23,71177,Procurement,region_5,Bachelor's,m,other,1,27,NaN,1,0,0,70,0
29,74759,Sales_Marketing,region_4,Bachelor's,m,sourcing,1,26,NaN,1,0,0,44,0
32,35465,Sales_Marketing,region_7,NaN,f,sourcing,1,24,1.0,2,0,0,48,0
43,17423,Sales_Marketing,region_2,NaN,m,other,3,24,2.0,2,0,0,48,0
56,45709,Sales_Marketing,region_31,Bachelor's,f,other,1,29,NaN,1,0,0,49,0
58,26599,Sales_Marketing,region_16,Bachelor's,m,other,2,27,NaN,1,1,0,47,0
62,9150,Analytics,region_22,Bachelor's,f,other,1,28,NaN,1,1,0,80,0
66,77981,Finance,region_22,Bachelor's,m,other,1,27,NaN,1,1,1,58,1

In [11]:
### check avg % of people promoted with NA in previous ye rating vs without NA

print(np.mean(_['is_promoted']),np.mean(train[~train.education.isnull()]['is_promoted']))

0.07091737150292778 0.08675738086604706

In [12]:
### check avg % of people promoted with NA in education vs without NA

print(np.mean(a['is_promoted']),np.mean(train[~train.education.isnull()]['is_promoted']))

0.0506434205064342 0.08675738086604706

In [13]:
## For education we will use unknown for all missing values and 9999 for prev year training

train['education'] = train.education.fillna('unknown')
train['previous_year_rating'] = train.previous_year_rating.fillna(9999)

test['education'] = test.education.fillna('unknown')
test['previous_year_rating'] = test.previous_year_rating.fillna(9999)

In [14]:
### merge dataframes for ease of processing
Y = train['is_promoted'].values
train.drop('is_promoted',inplace=True,axis=1)
train['train'] = 'train'
test['train'] = 'test'
merged = pd.concat([train,test])
merged.shape

(78298, 14)

In [15]:
cat_cols = [i for i in merged.columns if merged[i].dtypes == 'object']+['KPIs_met >80%','awards_won?','previous_year_rating']
cat_cols

['department',
 'region',
 'education',
 'gender',
 'recruitment_channel',
 'train',
 'KPIs_met >80%',
 'awards_won?',
 'previous_year_rating']

In [16]:
cat_cols.remove('train')
print(cat_cols)
#cat_idx = [merged.columns.get_loc(c) for c in merged.columns if c in cat_cols]

['department', 'region', 'education', 'gender', 'recruitment_channel', 'KPIs_met >80%', 'awards_won?', 'previous_year_rating']

In [17]:
merged.head()

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,train
0,65438,Sales_Marketing,region_7,Masters_above,f,sourcing,1,35,5.0,8,1,0,49,train
1,65141,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,0,60,train
2,7513,Sales_Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,0,50,train
3,2542,Sales_Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,0,50,train
4,48945,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,0,73,train

In [18]:
tr_cols = [i for i in merged.columns]
tr_cols.remove('employee_id')
tr  = merged[merged['train']=='train']
te = merged[merged['train']=='test']
tr.drop('train',axis=1,inplace=True)
te.drop('train',axis=1,inplace=True)

print(tr_cols)

### ###
tr_cols.remove('train')
X_train = tr[tr_cols]
Y_train = Y
X_test = te[tr_cols]

#cat_idx = [X_train.columns.get_loc(c) for c in X_train.columns if c in cat_cols]
cat_idx = [X_train.columns.get_loc(c) for c in cat_cols]

train_pool = Pool(X_train, Y_train, cat_features=cat_idx)

C:\Users\ADMIN\Anaconda3\envs\Pytorch_env\lib\site-packages\pandas\core\frame.py:3697: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

['department', 'region', 'education', 'gender', 'recruitment_channel', 'no_of_trainings', 'age', 'previous_year_rating', 'length_of_service', 'KPIs_met >80%', 'awards_won?', 'avg_training_score', 'train']

In [19]:
X_train.iloc[:,cat_idx].head()

,department,region,education,gender,recruitment_channel,KPIs_met >80%,awards_won?,previous_year_rating
0,Sales_Marketing,region_7,Masters_above,f,sourcing,1,0,5.0
1,Operations,region_22,Bachelor's,m,other,0,0,5.0
2,Sales_Marketing,region_19,Bachelor's,m,sourcing,0,0,3.0
3,Sales_Marketing,region_23,Bachelor's,m,other,0,0,1.0
4,Technology,region_26,Bachelor's,m,other,0,0,3.0

In [20]:
X_train.head()

,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score
0,Sales_Marketing,region_7,Masters_above,f,sourcing,1,35,5.0,8,1,0,49
1,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,0,60
2,Sales_Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,0,50
3,Sales_Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,0,50
4,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,0,73

In [21]:
cat_idx

[0, 1, 2, 3, 4, 9, 10, 7]

In [22]:
# def pre_process(df,cat_cols):
#     one_hot_encoded_training_predictors = pd.get_dummies(df[cat_cols])
#     df.drop(cat_cols,inplace=True,axis=1)
#     _ = pd.concat([df,one_hot_encoded_training_predictors],1)
#     new_tr, new_tst = _[_['train']=='train'],_[_['train']=='test']
#     new_tr.drop('train',inplace=True,axis=1)
#     new_tst.drop('train',inplace=True,axis=1)
#     return new_tr, new_tst

In [23]:
# train_OHE,test_OHE = pre_process(merged,cat_cols)

In [24]:
def kfold_lcatboost(train_df,test_df, target,num_folds, stratified = False, debug= False,modelname="catboost"):
    # Divide in training/validation and test data
    train_df = train_df
    test_df = test_df
    print("Train shape: {}, test shape: {}".format(train_df.shape, test_df.shape))
    gc.collect()

    # Cross validation model
    if stratified:
        folds = StratifiedKFold(n_splits= num_folds, shuffle=True, random_state=seed)
    else:
        folds = KFold(n_splits= num_folds, shuffle=True, random_state=seed)
    # Create arrays and dataframes to store results
    oof_preds = np.zeros(train_df.shape[0])
    sub_preds = np.zeros(test_df.shape[0])
    feature_importance_df = pd.DataFrame()
    feats = [f for f in train_df.columns if f not in ['employee_id','index']]
    
    for n_fold, (train_idx, valid_idx) in enumerate(folds.split(train_df[feats], target)):
        train_x, train_y = train_df[feats].iloc[train_idx], target[train_idx]
        valid_x, valid_y = train_df[feats].iloc[valid_idx], target[valid_idx]

        # LightGBM parameters found by Bayesian optimization
        clf = CatBoostClassifier(
            #nthread=4,
            #class_weights = [1,2],
            bagging_temperature = 0.85,
            iterations=5000,
            learning_rate=0.01,
            l2_leaf_reg = 1,
            depth=10,
            loss_function='Logloss',
            eval_metric='F1',
            silent=False)
        #print(train_x.head())
        clf.fit(train_x, train_y, eval_set=[(train_x, train_y), (valid_x, valid_y)], 
            verbose= 100, early_stopping_rounds= 200,cat_features=cat_idx,use_best_model=True)

        oof_preds[valid_idx] = clf.predict_proba(valid_x)[:, 1]
        sub_preds += clf.predict_proba(test_df[feats])[:, 1] / folds.n_splits

        fold_importance_df = pd.DataFrame()
        fold_importance_df["feature"] = feats
        fold_importance_df["importance"] = clf.feature_importances_
        fold_importance_df["fold"] = n_fold + 1
        feature_importance_df = pd.concat([feature_importance_df, fold_importance_df], axis=0)
        print('Fold %2d F-score : %.6f' % (n_fold + 1, sklearn.metrics.f1_score(valid_y, (oof_preds[valid_idx]>0.3).astype(int))))
        del clf, train_x, train_y, valid_x, valid_y
        gc.collect()

    print('Full f1 score %.6f' % sklearn.metrics.f1_score(target, (oof_preds>0.3).astype(int)))
    
    # Write submission file and plot feature importance
    if not debug:
        _ = datetime.now().strftime('%Y%m%d%H%M%S')
        Fname = 'F:/AV/WNS/submission/'+str(modelname)+'_'+str(_)+'.csv'
        submission['is_promoted'] = sub_preds
        submission[['employee_id', 'is_promoted']].to_csv(Fname, index= False)
        oof = pd.DataFrame(oof_preds)
        score = sklearn.metrics.f1_score(target, (oof_preds>0.3).astype(int))
        oof.columns = [modelname+'_'+str(round(score,4))]
        OOF_Fname = 'F:/AV/WNS/oof/'+str(modelname)+'_'+str(_)+'.csv'
        oof.to_csv(OOF_Fname,index=False)
    #display_importances(feature_importance_df)
    return

In [25]:
import gc
oof = kfold_lcatboost(X_train,X_test, Y,num_folds=5, stratified = True, debug= False,modelname="catboost_5fld_baggingtemp0.85")

Train shape: (54808, 12), test shape: (23490, 12)
0:	learn: 0.1374502	test: 0.1374502	best: 0.1374502 (0)	test1: 0.1477833	total: 166ms	remaining: 13m 48s
100:	learn: 0.2474275	test: 0.2478373	best: 0.3049166 (1)	test1: 0.2846715	total: 24.4s	remaining: 19m 43s
200:	learn: 0.3982888	test: 0.3982888	best: 0.3982888 (200)	test1: 0.4057725	total: 59.2s	remaining: 23m 33s
300:	learn: 0.4469320	test: 0.4482187	best: 0.4482187 (290)	test1: 0.4544709	total: 1m 41s	remaining: 26m 32s
400:	learn: 0.4717405	test: 0.4722675	best: 0.4722675 (399)	test1: 0.4781906	total: 2m 23s	remaining: 27m 26s
500:	learn: 0.4858529	test: 0.4871847	best: 0.4871847 (496)	test1: 0.4928230	total: 3m 4s	remaining: 27m 34s
600:	learn: 0.4900262	test: 0.4922582	best: 0.4922582 (591)	test1: 0.4992076	total: 3m 43s	remaining: 27m 16s
700:	learn: 0.4932663	test: 0.4954865	best: 0.4954865 (700)	test1: 0.5082612	total: 4m 19s	remaining: 26m 29s
800:	learn: 0.4961893	test: 0.4968944	best: 0.4971955 (798)	test1: 0.5094340	total: 4m 59s	remaining: 26m 11s
900:	learn: 0.4997999	test: 0.4988000	best: 0.4988000 (894)	test1: 0.5121378	total: 5m 39s	remaining: 25m 42s
1000:	learn: 0.5034937	test: 0.4999001	best: 0.5000000 (995)	test1: 0.5133020	total: 6m 22s	remaining: 25m 26s
1100:	learn: 0.5068684	test: 0.5013972	best: 0.5013972 (1046)	test1: 0.5179407	total: 7m 14s	remaining: 25m 39s
1200:	learn: 0.5133796	test: 0.5057700	best: 0.5058706 (1194)	test1: 0.5190959	total: 8m 16s	remaining: 26m 9s
1300:	learn: 0.5195420	test: 0.5079365	best: 0.5080373 (1288)	test1: 0.5178849	total: 9m 22s	remaining: 26m 38s
1400:	learn: 0.5264192	test: 0.5119589	best: 0.5123542 (1395)	test1: 0.5205267	total: 10m 28s	remaining: 26m 55s
1500:	learn: 0.5327596	test: 0.5153785	best: 0.5154802 (1492)	test1: 0.5224111	total: 11m 36s	remaining: 27m 3s
1600:	learn: 0.5376218	test: 0.5159512	best: 0.5162434 (1591)	test1: 0.5216049	total: 12m 42s	remaining: 26m 58s
1700:	learn: 0.5416019	test: 0.5188679	best: 0.5188679 (1699)	test1: 0.5261538	total: 13m 49s	remaining: 26m 49s
1800:	learn: 0.5464057	test: 0.5202199	best: 0.5202199 (1800)	test1: 0.5261538	total: 14m 55s	remaining: 26m 31s
1900:	learn: 0.5536919	test: 0.5219608	best: 0.5219608 (1900)	test1: 0.5261538	total: 16m 1s	remaining: 26m 7s
2000:	learn: 0.5585239	test: 0.5223354	best: 0.5232034 (1966)	test1: 0.5257494	total: 17m 7s	remaining: 25m 39s
2100:	learn: 0.5639357	test: 0.5241730	best: 0.5242756 (2066)	test1: 0.5261538	total: 18m 12s	remaining: 25m 7s
2200:	learn: 0.5669532	test: 0.5248338	best: 0.5252249 (2169)	test1: 0.5272867	total: 19m 12s	remaining: 24m 25s
2300:	learn: 0.5699581	test: 0.5249364	best: 0.5256160 (2278)	test1: 0.5272867	total: 20m 17s	remaining: 23m 47s
2400:	learn: 0.5741445	test: 0.5255132	best: 0.5256160 (2278)	test1: 0.5306748	total: 21m 22s	remaining: 23m 8s
2500:	learn: 0.5765287	test: 0.5261923	best: 0.5264804 (2477)	test1: 0.5318008	total: 22m 26s	remaining: 22m 25s
2600:	learn: 0.5786879	test: 0.5278157	best: 0.5278157 (2594)	test1: 0.5329250	total: 23m 31s	remaining: 21m 42s
2700:	learn: 0.5824508	test: 0.5288387	best: 0.5292284 (2686)	test1: 0.5333333	total: 24m 36s	remaining: 20m 56s
2800:	learn: 0.5852369	test: 0.5306599	best: 0.5309459 (2781)	test1: 0.5329250	total: 25m 40s	remaining: 20m 9s
2900:	learn: 0.5896519	test: 0.5315963	best: 0.5318818 (2892)	test1: 0.5329250	total: 26m 47s	remaining: 19m 23s
3000:	learn: 0.5928290	test: 0.5321672	best: 0.5321672 (2988)	test1: 0.5333333	total: 27m 54s	remaining: 18m 35s
3100:	learn: 0.5973054	test: 0.5327375	best: 0.5327375 (3008)	test1: 0.5329250	total: 29m	remaining: 17m 45s
3200:	learn: 0.6014925	test: 0.5327375	best: 0.5327375 (3008)	test1: 0.5321101	total: 30m 1s	remaining: 16m 52s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.532737517
bestIteration = 3008

Shrink model to first 3009 iterations.
Fold  1 F-score : 0.541322
0:	learn: 0.1905218	test: 0.1897006	best: 0.1897006 (0)	test1: 0.1668283	total: 222ms	remaining: 18m 30s
100:	learn: 0.2676511	test: 0.2676511	best: 0.2676511 (100)	test1: 0.2335217	total: 24.1s	remaining: 19m 29s
200:	learn: 0.3794073	test: 0.3821244	best: 0.3824736 (199)	test1: 0.3848145	total: 53.5s	remaining: 21m 16s
300:	learn: 0.4526511	test: 0.4542457	best: 0.4542457 (300)	test1: 0.4373957	total: 1m 29s	remaining: 23m 21s
400:	learn: 0.4902552	test: 0.4906570	best: 0.4906570 (400)	test1: 0.4718367	total: 2m 3s	remaining: 23m 33s
500:	learn: 0.4989015	test: 0.4987013	best: 0.4987013 (494)	test1: 0.4780488	total: 2m 36s	remaining: 23m 25s
600:	learn: 0.5031847	test: 0.5034826	best: 0.5034826 (599)	test1: 0.4817518	total: 3m 4s	remaining: 22m 29s
700:	learn: 0.5041750	test: 0.5050666	best: 0.5050666 (700)	test1: 0.4850445	total: 3m 35s	remaining: 22m 1s
800:	learn: 0.5062537	test: 0.5061532	best: 0.5065502 (780)	test1: 0.4850445	total: 4m 4s	remaining: 21m 23s
900:	learn: 0.5090117	test: 0.5088101	best: 0.5088101 (899)	test1: 0.4858757	total: 4m 40s	remaining: 21m 15s
1000:	learn: 0.5120601	test: 0.5113614	best: 0.5113614 (1000)	test1: 0.4858757	total: 5m 18s	remaining: 21m 13s
1100:	learn: 0.5167521	test: 0.5129319	best: 0.5129319 (1099)	test1: 0.4891392	total: 6m 12s	remaining: 21m 57s
1200:	learn: 0.5207473	test: 0.5153785	best: 0.5156712 (1192)	test1: 0.4891392	total: 7m 11s	remaining: 22m 44s
1300:	learn: 0.5233608	test: 0.5176146	best: 0.5176146 (1284)	test1: 0.4883534	total: 8m 19s	remaining: 23m 39s
1400:	learn: 0.5254902	test: 0.5205264	best: 0.5205264 (1394)	test1: 0.4863563	total: 9m 26s	remaining: 24m 15s
1500:	learn: 0.5297107	test: 0.5215856	best: 0.5219780 (1479)	test1: 0.4883534	total: 10m 35s	remaining: 24m 42s
1600:	learn: 0.5334373	test: 0.5229502	best: 0.5232399 (1589)	test1: 0.4899598	total: 11m 44s	remaining: 24m 56s
1700:	learn: 0.5399845	test: 0.5246865	best: 0.5246865 (1672)	test1: 0.4911717	total: 12m 53s	remaining: 25m
1800:	learn: 0.5453842	test: 0.5251615	best: 0.5251615 (1764)	test1: 0.4907779	total: 14m 2s	remaining: 24m 56s
1900:	learn: 0.5501543	test: 0.5266041	best: 0.5269953 (1875)	test1: 0.4903846	total: 15m 10s	remaining: 24m 43s
2000:	learn: 0.5547866	test: 0.5277561	best: 0.5280438 (1989)	test1: 0.4899920	total: 16m 18s	remaining: 24m 25s
2100:	learn: 0.5596014	test: 0.5296643	best: 0.5296643 (2096)	test1: 0.4899920	total: 17m 26s	remaining: 24m 3s
2200:	learn: 0.5649933	test: 0.5306043	best: 0.5309942 (2184)	test1: 0.4912000	total: 18m 35s	remaining: 23m 38s
2300:	learn: 0.5693069	test: 0.5321387	best: 0.5321387 (2298)	test1: 0.4924061	total: 19m 42s	remaining: 23m 7s
2400:	learn: 0.5722972	test: 0.5332814	best: 0.5332814 (2391)	test1: 0.4916201	total: 20m 50s	remaining: 22m 33s
2500:	learn: 0.5759242	test: 0.5335668	best: 0.5344224 (2445)	test1: 0.4916201	total: 21m 57s	remaining: 21m 56s
2600:	learn: 0.5812547	test: 0.5348114	best: 0.5348114 (2600)	test1: 0.4916201	total: 23m 5s	remaining: 21m 17s
2700:	learn: 0.5840407	test: 0.5356657	best: 0.5362347 (2670)	test1: 0.4916201	total: 24m 13s	remaining: 20m 36s
2800:	learn: 0.5875047	test: 0.5372671	best: 0.5373714 (2775)	test1: 0.4928230	total: 25m 21s	remaining: 19m 54s
2900:	learn: 0.5898929	test: 0.5368033	best: 0.5375509 (2810)	test1: 0.4928230	total: 26m 29s	remaining: 19m 10s
3000:	learn: 0.5939666	test: 0.5370874	best: 0.5376553 (2941)	test1: 0.4940239	total: 27m 35s	remaining: 18m 22s
3100:	learn: 0.5971210	test: 0.5368033	best: 0.5378347 (3050)	test1: 0.4940239	total: 28m 41s	remaining: 17m 34s
3200:	learn: 0.5994774	test: 0.5369831	best: 0.5378347 (3050)	test1: 0.4936306	total: 29m 46s	remaining: 16m 44s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.5378346915
bestIteration = 3050

Shrink model to first 3051 iterations.
Fold  2 F-score : 0.514962
0:	learn: 0.2347032	test: 0.2343001	best: 0.2343001 (0)	test1: 0.2756757	total: 340ms	remaining: 28m 19s
100:	learn: 0.2386657	test: 0.2394928	best: 0.2399624 (95)	test1: 0.2794118	total: 22.3s	remaining: 18m 3s
200:	learn: 0.3594127	test: 0.3604906	best: 0.3604906 (200)	test1: 0.3889845	total: 51.5s	remaining: 20m 29s
300:	learn: 0.4360902	test: 0.4370695	best: 0.4373957 (295)	test1: 0.4801298	total: 1m 30s	remaining: 23m 30s
400:	learn: 0.4604317	test: 0.4622332	best: 0.4622332 (399)	test1: 0.5063694	total: 2m 6s	remaining: 24m 6s

500:	learn: 0.4805353	test: 0.4790905	best: 0.4790905 (492)	test1: 0.5200946	total: 2m 39s	remaining: 23m 53s
600:	learn: 0.4877852	test: 0.4861588	best: 0.4861588 (599)	test1: 0.5212598	total: 3m 15s	remaining: 23m 48s
700:	learn: 0.4930625	test: 0.4920539	best: 0.4920539 (699)	test1: 0.5220126	total: 3m 50s	remaining: 23m 32s
800:	learn: 0.4956853	test: 0.4951846	best: 0.4953834 (788)	test1: 0.5220126	total: 4m 25s	remaining: 23m 10s
900:	learn: 0.4991994	test: 0.4966927	best: 0.4966927 (881)	test1: 0.5227630	total: 5m 1s	remaining: 22m 53s
1000:	learn: 0.5012000	test: 0.4980981	best: 0.4980981 (999)	test1: 0.5227630	total: 5m 40s	remaining: 22m 40s
1100:	learn: 0.5032954	test: 0.4992000	best: 0.4995001 (1097)	test1: 0.5250784	total: 6m 25s	remaining: 22m 46s
1200:	learn: 0.5097416	test: 0.5012982	best: 0.5012982 (1185)	test1: 0.5242567	total: 7m 22s	remaining: 23m 18s
1300:	learn: 0.5162312	test: 0.5059713	best: 0.5062687 (1299)	test1: 0.5245902	total: 8m 26s	remaining: 23m 59s
1400:	learn: 0.5216877	test: 0.5084409	best: 0.5086430 (1390)	test1: 0.5268901	total: 9m 29s	remaining: 24m 22s
1500:	learn: 0.5276796	test: 0.5120792	best: 0.5123738 (1489)	test1: 0.5303266	total: 10m 34s	remaining: 24m 39s
1600:	learn: 0.5331508	test: 0.5139356	best: 0.5140372 (1572)	test1: 0.5314685	total: 11m 39s	remaining: 24m 44s
1700:	learn: 0.5366901	test: 0.5141276	best: 0.5142292 (1674)	test1: 0.5329202	total: 12m 45s	remaining: 24m 45s
1800:	learn: 0.5400351	test: 0.5157853	best: 0.5157853 (1794)	test1: 0.5329202	total: 13m 54s	remaining: 24m 41s
1900:	learn: 0.5434402	test: 0.5166634	best: 0.5166634 (1884)	test1: 0.5325077	total: 15m 5s	remaining: 24m 36s
2000:	learn: 0.5484496	test: 0.5186060	best: 0.5186060 (1990)	test1: 0.5336427	total: 16m 17s	remaining: 24m 25s
2100:	learn: 0.5523773	test: 0.5190870	best: 0.5191891 (2021)	test1: 0.5332303	total: 17m 28s	remaining: 24m 6s
2200:	learn: 0.5550627	test: 0.5198584	best: 0.5199607 (2197)	test1: 0.5332303	total: 18m 38s	remaining: 23m 42s
2300:	learn: 0.5577367	test: 0.5198584	best: 0.5199607 (2197)	test1: 0.5328185	total: 19m 51s	remaining: 23m 17s
2400:	learn: 0.5603995	test: 0.5208170	best: 0.5209193 (2343)	test1: 0.5324074	total: 21m 5s	remaining: 22m 49s
2500:	learn: 0.5628834	test: 0.5208170	best: 0.5209193 (2343)	test1: 0.5357968	total: 22m 17s	remaining: 22m 16s
2600:	learn: 0.5646428	test: 0.5225579	best: 0.5225579 (2584)	test1: 0.5353846	total: 23m 29s	remaining: 21m 39s
2700:	learn: 0.5688634	test: 0.5237162	best: 0.5240055 (2677)	test1: 0.5365104	total: 24m 42s	remaining: 21m 2s
2800:	learn: 0.5744721	test: 0.5248727	best: 0.5251615 (2751)	test1: 0.5365104	total: 25m 56s	remaining: 20m 22s
2900:	learn: 0.5783681	test: 0.5251615	best: 0.5251615 (2751)	test1: 0.5376344	total: 27m 9s	remaining: 19m 39s
3000:	learn: 0.5814394	test: 0.5266041	best: 0.5266041 (2968)	test1: 0.5376344	total: 28m 22s	remaining: 18m 53s
3100:	learn: 0.5851446	test: 0.5283314	best: 0.5286189 (3092)	test1: 0.5372218	total: 29m 34s	remaining: 18m 6s
3200:	learn: 0.5875919	test: 0.5283314	best: 0.5286189 (3092)	test1: 0.5368098	total: 30m 46s	remaining: 17m 17s
3300:	learn: 0.5905156	test: 0.5290902	best: 0.5291935 (3260)	test1: 0.5368098	total: 32m	remaining: 16m 28s
3400:	learn: 0.5936502	test: 0.5297677	best: 0.5297677 (3397)	test1: 0.5368098	total: 33m 11s	remaining: 15m 36s
3500:	learn: 0.5953855	test: 0.5305247	best: 0.5305247 (3492)	test1: 0.5368098	total: 34m 22s	remaining: 14m 42s
3600:	learn: 0.5970765	test: 0.5305247	best: 0.5312012 (3552)	test1: 0.5368098	total: 35m 33s	remaining: 13m 48s
3700:	learn: 0.5986522	test: 0.5307077	best: 0.5313840 (3683)	test1: 0.5368098	total: 36m 45s	remaining: 12m 54s
3800:	learn: 0.6002244	test: 0.5318527	best: 0.5318527 (3779)	test1: 0.5368098	total: 37m 55s	remaining: 11m 57s
3900:	learn: 0.6016807	test: 0.5324245	best: 0.5327103 (3866)	test1: 0.5368098	total: 39m 6s	remaining: 11m 1s
4000:	learn: 0.6024636	test: 0.5330997	best: 0.5330997 (3991)	test1: 0.5368098	total: 40m 20s	remaining: 10m 4s
4100:	learn: 0.6055866	test: 0.5328140	best: 0.5330997 (3991)	test1: 0.5356869	total: 41m 32s	remaining: 9m 6s
4200:	learn: 0.6072558	test: 0.5330997	best: 0.5333852 (4122)	test1: 0.5356869	total: 42m 44s	remaining: 8m 7s
4300:	learn: 0.6084046	test: 0.5342412	best: 0.5342412 (4291)	test1: 0.5348659	total: 43m 56s	remaining: 7m 8s
4400:	learn: 0.6102136	test: 0.5348114	best: 0.5350962 (4371)	test1: 0.5348659	total: 45m 7s	remaining: 6m 8s
4500:	learn: 0.6113894	test: 0.5345264	best: 0.5350962 (4371)	test1: 0.5348659	total: 46m 18s	remaining: 5m 7s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.5350962473
bestIteration = 4371

Shrink model to first 4372 iterations.
Fold  3 F-score : 0.537415
0:	learn: 0.2420775	test: 0.2420775	best: 0.2420775 (0)	test1: 0.2054434	total: 127ms	remaining: 10m 33s
100:	learn: 0.2722875	test: 0.2727482	best: 0.2727482 (100)	test1: 0.2436739	total: 26.8s	remaining: 21m 40s
200:	learn: 0.4189873	test: 0.4199873	best: 0.4209861 (198)	test1: 0.3729402	total: 1m 2s	remaining: 24m 48s
300:	learn: 0.4708282	test: 0.4718597	best: 0.4718597 (300)	test1: 0.4376040	total: 1m 45s	remaining: 27m 24s
400:	learn: 0.4917571	test: 0.4920603	best: 0.4923633 (396)	test1: 0.4602785	total: 2m 23s	remaining: 27m 28s
500:	learn: 0.5005998	test: 0.5013972	best: 0.5014973 (496)	test1: 0.4649266	total: 3m	remaining: 27m 2s
600:	learn: 0.5054726	test: 0.5055688	best: 0.5055688 (597)	test1: 0.4711617	total: 3m 37s	remaining: 26m 28s
700:	learn: 0.5075457	test: 0.5070478	best: 0.5071485 (678)	test1: 0.4748784	total: 4m 14s	remaining: 26m
800:	learn: 0.5107899	test: 0.5094078	best: 0.5094078 (783)	test1: 0.4744939	total: 4m 51s	remaining: 25m 29s
900:	learn: 0.5137325	test: 0.5112693	best: 0.5112693 (886)	test1: 0.4757282	total: 5m 29s	remaining: 25m
1000:	learn: 0.5160781	test: 0.5130332	best: 0.5130332 (989)	test1: 0.4761905	total: 6m 9s	remaining: 24m 34s
1100:	learn: 0.5177305	test: 0.5152770	best: 0.5153785 (1082)	test1: 0.4786463	total: 6m 59s	remaining: 24m 44s
1200:	learn: 0.5220978	test: 0.5184894	best: 0.5188828 (1196)	test1: 0.4786463	total: 8m	remaining: 25m 20s
1300:	learn: 0.5258621	test: 0.5198428	best: 0.5198428 (1297)	test1: 0.4803213	total: 9m 2s	remaining: 25m 41s
1400:	learn: 0.5302853	test: 0.5211931	best: 0.5211931 (1348)	test1: 0.4778761	total: 10m 8s	remaining: 26m 1s
1500:	learn: 0.5331513	test: 0.5235110	best: 0.5236136 (1496)	test1: 0.4803213	total: 11m 12s	remaining: 26m 7s
1600:	learn: 0.5392385	test: 0.5239028	best: 0.5241082 (1584)	test1: 0.4803843	total: 12m 11s	remaining: 25m 52s
1700:	learn: 0.5433056	test: 0.5268712	best: 0.5271590 (1696)	test1: 0.4812150	total: 13m 14s	remaining: 25m 41s
1800:	learn: 0.5468599	test: 0.5282872	best: 0.5285742 (1778)	test1: 0.4824281	total: 14m 19s	remaining: 25m 25s
1900:	learn: 0.5505401	test: 0.5299045	best: 0.5299045 (1890)	test1: 0.4824281	total: 15m 26s	remaining: 25m 10s
2000:	learn: 0.5551068	test: 0.5319066	best: 0.5319066 (1968)	test1: 0.4840764	total: 16m 34s	remaining: 24m 49s
2100:	learn: 0.5582645	test: 0.5343956	best: 0.5346804 (2097)	test1: 0.4832536	total: 17m 43s	remaining: 24m 27s
2200:	learn: 0.5626197	test: 0.5348611	best: 0.5353261 (2132)	test1: 0.4820431	total: 18m 50s	remaining: 23m 57s
2300:	learn: 0.5654250	test: 0.5357905	best: 0.5359984 (2267)	test1: 0.4844622	total: 19m 59s	remaining: 23m 27s
2400:	learn: 0.5695238	test: 0.5373886	best: 0.5373886 (2400)	test1: 0.4844622	total: 21m 9s	remaining: 22m 54s
2500:	learn: 0.5718090	test: 0.5391607	best: 0.5391607 (2499)	test1: 0.4860558	total: 22m 21s	remaining: 22m 20s
2600:	learn: 0.5746297	test: 0.5390565	best: 0.5395475 (2558)	test1: 0.4844622	total: 23m 30s	remaining: 21m 40s
2700:	learn: 0.5781398	test: 0.5406763	best: 0.5406763 (2700)	test1: 0.4856688	total: 24m 41s	remaining: 21m
2800:	learn: 0.5802913	test: 0.5411356	best: 0.5414173 (2790)	test1: 0.4868735	total: 25m 50s	remaining: 20m 17s
2900:	learn: 0.5830816	test: 0.5418757	best: 0.5421571 (2890)	test1: 0.4868735	total: 27m	remaining: 19m 32s
3000:	learn: 0.5864407	test: 0.5429288	best: 0.5432099 (2996)	test1: 0.4876886	total: 28m 8s	remaining: 18m 44s
3100:	learn: 0.5896280	test: 0.5436669	best: 0.5441233 (3067)	test1: 0.4868735	total: 29m 18s	remaining: 17m 56s

3200:	learn: 0.5912162	test: 0.5446497	best: 0.5447546 (3148)	test1: 0.4868735	total: 30m 25s	remaining: 17m 6s
3300:	learn: 0.5939666	test: 0.5454196	best: 0.5455245 (3293)	test1: 0.4868735	total: 31m 35s	remaining: 16m 15s
3400:	learn: 0.5985429	test: 0.5465385	best: 0.5465385 (3379)	test1: 0.4868735	total: 32m 43s	remaining: 15m 23s
3500:	learn: 0.6010073	test: 0.5470973	best: 0.5472713 (3491)	test1: 0.4868735	total: 33m 52s	remaining: 14m 30s
3600:	learn: 0.6049107	test: 0.5469231	best: 0.5472713 (3491)	test1: 0.4868735	total: 34m 59s	remaining: 13m 35s
3700:	learn: 0.6085343	test: 0.5473765	best: 0.5477609 (3645)	test1: 0.4868735	total: 36m 8s	remaining: 12m 41s
3800:	learn: 0.6105965	test: 0.5490121	best: 0.5490121 (3782)	test1: 0.4880763	total: 37m 16s	remaining: 11m 45s
3900:	learn: 0.6129092	test: 0.5494632	best: 0.5498466 (3845)	test1: 0.4876886	total: 38m 23s	remaining: 10m 49s
4000:	learn: 0.6145602	test: 0.5504025	best: 0.5504025 (3974)	test1: 0.4876886	total: 39m 31s	remaining: 9m 52s
4100:	learn: 0.6158390	test: 0.5504025	best: 0.5508523 (4063)	test1: 0.4873016	total: 40m 39s	remaining: 8m 54s
4200:	learn: 0.6186441	test: 0.5506802	best: 0.5509579 (4106)	test1: 0.4873016	total: 41m 41s	remaining: 7m 55s
4300:	learn: 0.6205374	test: 0.5505747	best: 0.5509579 (4106)	test1: 0.4885012	total: 42m 45s	remaining: 6m 56s
4400:	learn: 0.6225652	test: 0.5519617	best: 0.5519617 (4399)	test1: 0.4896989	total: 43m 49s	remaining: 5m 57s
4500:	learn: 0.6253438	test: 0.5519617	best: 0.5519617 (4399)	test1: 0.4908947	total: 44m 53s	remaining: 4m 58s
4600:	learn: 0.6268547	test: 0.5534519	best: 0.5534519 (4587)	test1: 0.4896989	total: 45m 57s	remaining: 3m 59s
4700:	learn: 0.6286132	test: 0.5541109	best: 0.5541109 (4700)	test1: 0.4896989	total: 46m 59s	remaining: 2m 59s
4800:	learn: 0.6299817	test: 0.5541754	best: 0.5541754 (4751)	test1: 0.4908947	total: 48m	remaining: 1m 59s
4900:	learn: 0.6309828	test: 0.5540050	best: 0.5542813 (4855)	test1: 0.4908947	total: 49m 4s	remaining: 59.5s
4999:	learn: 0.6317327	test: 0.5546636	best: 0.5546636 (4956)	test1: 0.4908947	total: 50m 9s	remaining: 0us

bestTest = 0.5546636086
bestIteration = 4956

Shrink model to first 4957 iterations.
Fold  4 F-score : 0.523582
0:	learn: 0.1993355	test: 0.1993355	best: 0.1993355 (0)	test1: 0.1703775	total: 219ms	remaining: 18m 13s
100:	learn: 0.2520382	test: 0.2520382	best: 0.2544778 (97)	test1: 0.2272727	total: 21.8s	remaining: 17m 35s
200:	learn: 0.3806438	test: 0.3813431	best: 0.3813431 (200)	test1: 0.3664921	total: 53.6s	remaining: 21m 19s
300:	learn: 0.4326019	test: 0.4343287	best: 0.4346555 (299)	test1: 0.4295302	total: 1m 28s	remaining: 23m 8s
400:	learn: 0.4660393	test: 0.4675112	best: 0.4675112 (399)	test1: 0.4567189	total: 2m 3s	remaining: 23m 38s
500:	learn: 0.4860719	test: 0.4859738	best: 0.4859738 (500)	test1: 0.4714519	total: 2m 37s	remaining: 23m 35s
600:	learn: 0.4943820	test: 0.4940799	best: 0.4940799 (600)	test1: 0.4776604	total: 3m 11s	remaining: 23m 22s
700:	learn: 0.4987003	test: 0.4962948	best: 0.4965959 (693)	test1: 0.4862682	total: 3m 51s	remaining: 23m 39s
800:	learn: 0.5058706	test: 0.5030895	best: 0.5030895 (791)	test1: 0.4895330	total: 4m 29s	remaining: 23m 33s
900:	learn: 0.5068575	test: 0.5050746	best: 0.5051752 (859)	test1: 0.4907482	total: 5m 6s	remaining: 23m 14s
1000:	learn: 0.5094227	test: 0.5066561	best: 0.5066561 (1000)	test1: 0.4911433	total: 5m 48s	remaining: 23m 11s
1100:	learn: 0.5132568	test: 0.5094153	best: 0.5095163 (1084)	test1: 0.4935691	total: 6m 43s	remaining: 23m 49s
1200:	learn: 0.5160016	test: 0.5110847	best: 0.5111859 (1187)	test1: 0.4963971	total: 7m 49s	remaining: 24m 44s
1300:	learn: 0.5216365	test: 0.5131449	best: 0.5134387 (1293)	test1: 0.4996010	total: 8m 59s	remaining: 25m 34s
1400:	learn: 0.5269555	test: 0.5168539	best: 0.5168539 (1382)	test1: 0.5003984	total: 10m 10s	remaining: 26m 7s
1500:	learn: 0.5330207	test: 0.5179204	best: 0.5179204 (1499)	test1: 0.5015924	total: 11m 19s	remaining: 26m 24s
1600:	learn: 0.5383716	test: 0.5184164	best: 0.5184164 (1559)	test1: 0.5019857	total: 12m 30s	remaining: 26m 32s
1700:	learn: 0.5444315	test: 0.5211406	best: 0.5211406 (1690)	test1: 0.5031746	total: 13m 39s	remaining: 26m 29s
1800:	learn: 0.5493230	test: 0.5221152	best: 0.5221152 (1799)	test1: 0.5039620	total: 14m 48s	remaining: 26m 18s
1900:	learn: 0.5537987	test: 0.5250980	best: 0.5253872 (1889)	test1: 0.5039620	total: 15m 57s	remaining: 26m
2000:	learn: 0.5591852	test: 0.5264395	best: 0.5267280 (1990)	test1: 0.5047468	total: 17m 6s	remaining: 25m 38s
2100:	learn: 0.5640337	test: 0.5273048	best: 0.5273048 (2063)	test1: 0.5059289	total: 18m 14s	remaining: 25m 10s
2200:	learn: 0.5686986	test: 0.5287446	best: 0.5287446 (2194)	test1: 0.5059289	total: 19m 23s	remaining: 24m 39s
2300:	learn: 0.5744195	test: 0.5295037	best: 0.5296072 (2278)	test1: 0.5059289	total: 20m 31s	remaining: 24m 4s
2400:	learn: 0.5776681	test: 0.5297910	best: 0.5300781 (2367)	test1: 0.5059289	total: 21m 41s	remaining: 23m 28s
2500:	learn: 0.5822449	test: 0.5307557	best: 0.5307557 (2498)	test1: 0.5059289	total: 22m 51s	remaining: 22m 49s
2600:	learn: 0.5867925	test: 0.5313293	best: 0.5316159 (2573)	test1: 0.5071090	total: 23m 59s	remaining: 22m 7s
2700:	learn: 0.5893429	test: 0.5336192	best: 0.5339049 (2668)	test1: 0.5071090	total: 25m 8s	remaining: 21m 23s
2800:	learn: 0.5922585	test: 0.5347614	best: 0.5350467 (2790)	test1: 0.5071090	total: 26m 16s	remaining: 20m 37s
2900:	learn: 0.5954256	test: 0.5356170	best: 0.5361868 (2867)	test1: 0.5090623	total: 27m 24s	remaining: 19m 50s
3000:	learn: 0.5996262	test: 0.5373250	best: 0.5373250 (3000)	test1: 0.5086614	total: 28m 32s	remaining: 19m 1s
3100:	learn: 0.6009337	test: 0.5385962	best: 0.5385962 (3087)	test1: 0.5086614	total: 29m 41s	remaining: 18m 11s
3200:	learn: 0.6038017	test: 0.5384914	best: 0.5388802 (3120)	test1: 0.5086614	total: 30m 50s	remaining: 17m 19s
3300:	learn: 0.6079524	test: 0.5392385	best: 0.5392385 (3300)	test1: 0.5110063	total: 31m 58s	remaining: 16m 27s
3400:	learn: 0.6113068	test: 0.5409391	best: 0.5416101 (3389)	test1: 0.5106049	total: 33m 6s	remaining: 15m 33s
3500:	learn: 0.6138760	test: 0.5420706	best: 0.5423532 (3497)	test1: 0.5110063	total: 34m 8s	remaining: 14m 37s
3600:	learn: 0.6164358	test: 0.5424583	best: 0.5424583 (3597)	test1: 0.5106049	total: 35m 14s	remaining: 13m 41s
3700:	learn: 0.6185909	test: 0.5435878	best: 0.5435878 (3679)	test1: 0.5117739	total: 36m 20s	remaining: 12m 45s
3800:	learn: 0.6216415	test: 0.5445391	best: 0.5445391 (3747)	test1: 0.5121760	total: 37m 26s	remaining: 11m 48s
3900:	learn: 0.6256881	test: 0.5457010	best: 0.5457010 (3895)	test1: 0.5117739	total: 38m 31s	remaining: 10m 51s
4000:	learn: 0.6264442	test: 0.5458769	best: 0.5458769 (3949)	test1: 0.5129412	total: 39m 38s	remaining: 9m 53s
4100:	learn: 0.6278388	test: 0.5458769	best: 0.5459826 (4024)	test1: 0.5125392	total: 40m 46s	remaining: 8m 56s
4200:	learn: 0.6298464	test: 0.5474947	best: 0.5476006 (4192)	test1: 0.5125392	total: 41m 54s	remaining: 7m 58s
4300:	learn: 0.6308480	test: 0.5477756	best: 0.5480565 (4214)	test1: 0.5117371	total: 43m 4s	remaining: 6m 59s
4400:	learn: 0.6320979	test: 0.5481625	best: 0.5487239 (4386)	test1: 0.5117371	total: 44m 12s	remaining: 6m 1s
4500:	learn: 0.6344576	test: 0.5484432	best: 0.5487239 (4386)	test1: 0.5121378	total: 45m 21s	remaining: 5m 1s
4600:	learn: 0.6357013	test: 0.5494590	best: 0.5494590 (4585)	test1: 0.5105717	total: 46m 29s	remaining: 4m 1s
4700:	learn: 0.6379342	test: 0.5494590	best: 0.5498454 (4635)	test1: 0.5105717	total: 47m 37s	remaining: 3m 1s
4800:	learn: 0.6395349	test: 0.5501256	best: 0.5501256 (4795)	test1: 0.5094044	total: 48m 39s	remaining: 2m
4900:	learn: 0.6410163	test: 0.5501256	best: 0.5505119 (4879)	test1: 0.5094044	total: 49m 27s	remaining: 59.9s
4999:	learn: 0.6435949	test: 0.5510716	best: 0.5513514 (4950)	test1: 0.5113370	total: 50m 15s	remaining: 0us

bestTest = 0.5513513514
bestIteration = 4950

Shrink model to first 4951 iterations.
Fold  5 F-score : 0.520055
Full f1 score 0.527518