In [1]:
## imports

import numpy as np
import pandas as pd

from fastai.structured import *
from fastai.column_data import *
np.set_printoptions(threshold=50, edgeitems=20)
pd.set_option('display.max_columns', 100)
from lightgbm import LGBMClassifier
from datetime import datetime
from catboost import CatBoostClassifier, Pool, cv

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, roc_auc_score ,roc_curve,auc
from sklearn.model_selection import GridSearchCV,StratifiedKFold,KFold
from sklearn.preprocessing import LabelEncoder
seed = 45
#seed =145
% matplotlib inline
plt.style.use('fivethirtyeight')

In [3]:
### read data with some categorty name changes to raw files
PATH='F:/AV/WNS'
train_csv = 'train_catboost.csv'
test_csv = 'test_catboost.csv'
submit_csv = 'sample_submission_M0L0uXE.csv'

### read train, test and submission files
train = pd.read_csv(f'{PATH}/{train_csv}')
test = pd.read_csv(f'{PATH}/{test_csv}')
submission = pd.read_csv(f'{PATH}/{submit_csv}')

print("Shape of {}:{} {}:{} {}:{}".format('train',train.shape,'test',test.shape,'submission',submission.shape))

Shape of train:(54808, 14) test:(23490, 13) submission:(23490, 2)

In [4]:
### inspect data

train.head()

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,65438,Sales_Marketing,region_7,Masters_above,f,sourcing,1,35,5.0,8,1,0,49,0
1,65141,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,0,60,0
2,7513,Sales_Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,0,50,0
3,2542,Sales_Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,0,50,0
4,48945,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,0,73,0

In [5]:
### class balance

train['is_promoted'].value_counts()

## so approx 10% of past employees have been promoted

0    50140
1     4668
Name: is_promoted, dtype: int64

In [6]:
### lets check if there is any repeat in employees

len(train['employee_id'].unique()) == train.shape[0]

### so all IDs are unique

True

In [7]:
## null values

null_columns=train.columns[train.isnull().any()]
train[null_columns].isnull().sum()

## so 2 columns have null values

education               2409
previous_year_rating    4124
dtype: int64

In [8]:
### inspect null value columns
a = train[(train.education.isnull())]
_ = train[(train.education.isnull() | train.previous_year_rating.isnull())]

print(a.shape,_.shape)

(2409, 14) (6148, 14)

In [9]:
set(a.index).intersection(set(_.index)) == set(a.index)

### so everywhere where education is not present prev year rating is also not present, but vice-versa is not true

True

In [10]:
_.head(10)

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
10,29934,Technology,region_23,NaN,m,sourcing,1,30,NaN,1,0,0,77,0
21,33332,Operations,region_15,NaN,m,sourcing,1,41,4.0,11,0,0,57,0
23,71177,Procurement,region_5,Bachelor's,m,other,1,27,NaN,1,0,0,70,0
29,74759,Sales_Marketing,region_4,Bachelor's,m,sourcing,1,26,NaN,1,0,0,44,0
32,35465,Sales_Marketing,region_7,NaN,f,sourcing,1,24,1.0,2,0,0,48,0
43,17423,Sales_Marketing,region_2,NaN,m,other,3,24,2.0,2,0,0,48,0
56,45709,Sales_Marketing,region_31,Bachelor's,f,other,1,29,NaN,1,0,0,49,0
58,26599,Sales_Marketing,region_16,Bachelor's,m,other,2,27,NaN,1,1,0,47,0
62,9150,Analytics,region_22,Bachelor's,f,other,1,28,NaN,1,1,0,80,0
66,77981,Finance,region_22,Bachelor's,m,other,1,27,NaN,1,1,1,58,1

In [11]:
### check avg % of people promoted with NA in previous ye rating vs without NA

print(np.mean(_['is_promoted']),np.mean(train[~train.education.isnull()]['is_promoted']))

0.07091737150292778 0.08675738086604706

In [12]:
### check avg % of people promoted with NA in education vs without NA

print(np.mean(a['is_promoted']),np.mean(train[~train.education.isnull()]['is_promoted']))

0.0506434205064342 0.08675738086604706

In [13]:
## For education we will use unknown for all missing values and 9999 for prev year training

train['education'] = train.education.fillna('unknown')
train['previous_year_rating'] = train.previous_year_rating.fillna(9999)

test['education'] = test.education.fillna('unknown')
test['previous_year_rating'] = test.previous_year_rating.fillna(9999)

In [14]:
### merge dataframes for ease of processing
Y = train['is_promoted'].values
train.drop('is_promoted',inplace=True,axis=1)
train['train'] = 'train'
test['train'] = 'test'
merged = pd.concat([train,test])
merged.shape

(78298, 14)

In [15]:
cat_cols = [i for i in merged.columns if merged[i].dtypes == 'object']+['KPIs_met >80%','awards_won?','previous_year_rating']
cat_cols

['department',
 'region',
 'education',
 'gender',
 'recruitment_channel',
 'train',
 'KPIs_met >80%',
 'awards_won?',
 'previous_year_rating']

In [16]:
cat_cols.remove('train')
print(cat_cols)
#cat_idx = [merged.columns.get_loc(c) for c in merged.columns if c in cat_cols]

['department', 'region', 'education', 'gender', 'recruitment_channel', 'KPIs_met >80%', 'awards_won?', 'previous_year_rating']

In [17]:
merged.head()

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,train
0,65438,Sales_Marketing,region_7,Masters_above,f,sourcing,1,35,5.0,8,1,0,49,train
1,65141,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,0,60,train
2,7513,Sales_Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,0,50,train
3,2542,Sales_Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,0,50,train
4,48945,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,0,73,train

In [18]:
tr_cols = [i for i in merged.columns]
tr_cols.remove('employee_id')
tr  = merged[merged['train']=='train']
te = merged[merged['train']=='test']
tr.drop('train',axis=1,inplace=True)
te.drop('train',axis=1,inplace=True)

print(tr_cols)

### ###
tr_cols.remove('train')
X_train = tr[tr_cols]
Y_train = Y
X_test = te[tr_cols]

#cat_idx = [X_train.columns.get_loc(c) for c in X_train.columns if c in cat_cols]
cat_idx = [X_train.columns.get_loc(c) for c in cat_cols]

train_pool = Pool(X_train, Y_train, cat_features=cat_idx)

C:\Users\ADMIN\Anaconda3\envs\Pytorch_env\lib\site-packages\pandas\core\frame.py:3697: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

['department', 'region', 'education', 'gender', 'recruitment_channel', 'no_of_trainings', 'age', 'previous_year_rating', 'length_of_service', 'KPIs_met >80%', 'awards_won?', 'avg_training_score', 'train']

In [19]:
X_train.iloc[:,cat_idx].head()

,department,region,education,gender,recruitment_channel,KPIs_met >80%,awards_won?,previous_year_rating
0,Sales_Marketing,region_7,Masters_above,f,sourcing,1,0,5.0
1,Operations,region_22,Bachelor's,m,other,0,0,5.0
2,Sales_Marketing,region_19,Bachelor's,m,sourcing,0,0,3.0
3,Sales_Marketing,region_23,Bachelor's,m,other,0,0,1.0
4,Technology,region_26,Bachelor's,m,other,0,0,3.0

In [20]:
X_train.head()

,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score
0,Sales_Marketing,region_7,Masters_above,f,sourcing,1,35,5.0,8,1,0,49
1,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,0,60
2,Sales_Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,0,50
3,Sales_Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,0,50
4,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,0,73

In [21]:
cat_idx

[0, 1, 2, 3, 4, 9, 10, 7]

In [22]:
# def pre_process(df,cat_cols):
#     one_hot_encoded_training_predictors = pd.get_dummies(df[cat_cols])
#     df.drop(cat_cols,inplace=True,axis=1)
#     _ = pd.concat([df,one_hot_encoded_training_predictors],1)
#     new_tr, new_tst = _[_['train']=='train'],_[_['train']=='test']
#     new_tr.drop('train',inplace=True,axis=1)
#     new_tst.drop('train',inplace=True,axis=1)
#     return new_tr, new_tst

In [23]:
# train_OHE,test_OHE = pre_process(merged,cat_cols)

In [24]:
def kfold_catboost(train_df,test_df, target,num_folds, stratified = False, debug= False,modelname="catboost"):
    # Divide in training/validation and test data
    train_df = train_df
    test_df = test_df
    print("Train shape: {}, test shape: {}".format(train_df.shape, test_df.shape))
    gc.collect()

    # Cross validation model
    if stratified:
        folds = StratifiedKFold(n_splits= num_folds, shuffle=True, random_state=seed)
    else:
        folds = KFold(n_splits= num_folds, shuffle=True, random_state=seed)
    # Create arrays and dataframes to store results
    oof_preds = np.zeros(train_df.shape[0])
    sub_preds = np.zeros(test_df.shape[0])
    feature_importance_df = pd.DataFrame()
    feats = [f for f in train_df.columns if f not in ['employee_id','index']]
    
    for n_fold, (train_idx, valid_idx) in enumerate(folds.split(train_df[feats], target)):
        train_x, train_y = train_df[feats].iloc[train_idx], target[train_idx]
        valid_x, valid_y = train_df[feats].iloc[valid_idx], target[valid_idx]

        # LightGBM parameters found by Bayesian optimization
        clf = CatBoostClassifier(
            #nthread=4,
            #class_weights = [1,2],
            bagging_temperature = 1.25,
            iterations=5000,
            learning_rate=0.01,
            l2_leaf_reg = 1,
            depth=10,
            loss_function='Logloss',
            eval_metric='F1',
            silent=False)
        #print(train_x.head())
        clf.fit(train_x, train_y, eval_set=[(train_x, train_y), (valid_x, valid_y)], 
            verbose= 100, early_stopping_rounds= 200,cat_features=cat_idx,use_best_model=True)

        oof_preds[valid_idx] = clf.predict_proba(valid_x)[:, 1]
        sub_preds += clf.predict_proba(test_df[feats])[:, 1] / folds.n_splits

        fold_importance_df = pd.DataFrame()
        fold_importance_df["feature"] = feats
        fold_importance_df["importance"] = clf.feature_importances_
        fold_importance_df["fold"] = n_fold + 1
        feature_importance_df = pd.concat([feature_importance_df, fold_importance_df], axis=0)
        print('Fold %2d F-score : %.6f' % (n_fold + 1, sklearn.metrics.f1_score(valid_y, (oof_preds[valid_idx]>0.3).astype(int))))
        del clf, train_x, train_y, valid_x, valid_y
        gc.collect()

    print('Full f1 score %.6f' % sklearn.metrics.f1_score(target, (oof_preds>0.3).astype(int)))
    
    # Write submission file and plot feature importance
    if not debug:
        _ = datetime.now().strftime('%Y%m%d%H%M%S')
        Fname = 'F:/AV/WNS/submission/'+str(modelname)+'_'+str(_)+'.csv'
        submission['is_promoted'] = sub_preds
        submission[['employee_id', 'is_promoted']].to_csv(Fname, index= False)
        oof = pd.DataFrame(oof_preds)
        score = sklearn.metrics.f1_score(target, (oof_preds>0.3).astype(int))
        oof.columns = [modelname+'_'+str(round(score,4))]
        OOF_Fname = 'F:/AV/WNS/oof/'+str(modelname)+'_'+str(_)+'.csv'
        oof.to_csv(OOF_Fname,index=False)
    #display_importances(feature_importance_df)
    return

In [25]:
import gc
oof = kfold_catboost(X_train,X_test, Y,num_folds=5, stratified = True, debug= False,modelname="catboost_5fld_bagtemp")

Train shape: (54808, 12), test shape: (23490, 12)
0:	learn: 0.2019967	test: 0.2019967	best: 0.2019967 (0)	test1: 0.2454874	total: 124ms	remaining: 10m 21s
100:	learn: 0.2866941	test: 0.2870857	best: 0.2875429 (98)	test1: 0.3024302	total: 9.64s	remaining: 7m 47s
200:	learn: 0.4019629	test: 0.4026445	best: 0.4026445 (200)	test1: 0.4091293	total: 22.4s	remaining: 8m 55s
300:	learn: 0.4546205	test: 0.4571664	best: 0.4571664 (299)	test1: 0.4566285	total: 41s	remaining: 10m 40s
400:	learn: 0.4802271	test: 0.4814590	best: 0.4814590 (400)	test1: 0.4883907	total: 1m 2s	remaining: 11m 51s
500:	learn: 0.4927595	test: 0.4923572	best: 0.4923572 (500)	test1: 0.5031646	total: 1m 21s	remaining: 12m 14s
600:	learn: 0.4965905	test: 0.4947791	best: 0.4950813 (586)	test1: 0.5102362	total: 1m 40s	remaining: 12m 18s
700:	learn: 0.4995997	test: 0.4973948	best: 0.4973948 (691)	test1: 0.5141066	total: 2m 1s	remaining: 12m 25s
800:	learn: 0.5045872	test: 0.5006999	best: 0.5006999 (796)	test1: 0.5183450	total: 2m 23s	remaining: 12m 31s
900:	learn: 0.5086498	test: 0.5030920	best: 0.5030920 (896)	test1: 0.5209953	total: 2m 45s	remaining: 12m 30s
1000:	learn: 0.5134707	test: 0.5066667	best: 0.5066667 (995)	test1: 0.5232198	total: 3m 8s	remaining: 12m 32s
1100:	learn: 0.5200237	test: 0.5096249	best: 0.5099206 (1092)	test1: 0.5232198	total: 3m 36s	remaining: 12m 48s
1200:	learn: 0.5247836	test: 0.5131553	best: 0.5131553 (1197)	test1: 0.5240310	total: 4m 7s	remaining: 13m 2s
1300:	learn: 0.5290196	test: 0.5153132	best: 0.5156188 (1284)	test1: 0.5239567	total: 4m 37s	remaining: 13m 9s
1400:	learn: 0.5337243	test: 0.5173502	best: 0.5178466 (1366)	test1: 0.5246914	total: 5m 8s	remaining: 13m 11s
1500:	learn: 0.5394352	test: 0.5185185	best: 0.5185185 (1498)	test1: 0.5258288	total: 5m 37s	remaining: 13m 7s
1600:	learn: 0.5460539	test: 0.5204563	best: 0.5204563 (1598)	test1: 0.5269646	total: 6m 6s	remaining: 12m 57s
1700:	learn: 0.5504836	test: 0.5225084	best: 0.5225084 (1682)	test1: 0.5269646	total: 6m 33s	remaining: 12m 42s
1800:	learn: 0.5566256	test: 0.5254071	best: 0.5254071 (1797)	test1: 0.5300462	total: 7m 1s	remaining: 12m 28s
1900:	learn: 0.5621642	test: 0.5276362	best: 0.5279248 (1891)	test1: 0.5300462	total: 7m 28s	remaining: 12m 11s
2000:	learn: 0.5660161	test: 0.5297340	best: 0.5297340 (1999)	test1: 0.5289129	total: 7m 55s	remaining: 11m 53s
2100:	learn: 0.5712107	test: 0.5300215	best: 0.5305963 (2037)	test1: 0.5300462	total: 8m 23s	remaining: 11m 34s
2200:	learn: 0.5772883	test: 0.5319274	best: 0.5320312 (2189)	test1: 0.5300462	total: 8m 53s	remaining: 11m 18s
2300:	learn: 0.5821347	test: 0.5327869	best: 0.5327869 (2297)	test1: 0.5300462	total: 9m 20s	remaining: 10m 57s
2400:	learn: 0.5869483	test: 0.5339314	best: 0.5339314 (2357)	test1: 0.5300462	total: 9m 47s	remaining: 10m 36s
2500:	learn: 0.5910886	test: 0.5345029	best: 0.5347885 (2498)	test1: 0.5300462	total: 10m 14s	remaining: 10m 14s
2600:	learn: 0.5966292	test: 0.5360062	best: 0.5362911 (2594)	test1: 0.5304549	total: 10m 41s	remaining: 9m 52s
2700:	learn: 0.5992523	test: 0.5367561	best: 0.5367561 (2674)	test1: 0.5304549	total: 11m 9s	remaining: 9m 30s
2800:	learn: 0.6034290	test: 0.5381776	best: 0.5384615 (2785)	test1: 0.5300462	total: 11m 37s	remaining: 9m 7s
2900:	learn: 0.6084695	test: 0.5393128	best: 0.5393128 (2891)	test1: 0.5292308	total: 12m 5s	remaining: 8m 44s
3000:	learn: 0.6112760	test: 0.5399845	best: 0.5399845 (2992)	test1: 0.5306748	total: 12m 32s	remaining: 8m 21s
3100:	learn: 0.6135901	test: 0.5412951	best: 0.5412951 (3095)	test1: 0.5302682	total: 12m 59s	remaining: 7m 57s
3200:	learn: 0.6162941	test: 0.5409073	best: 0.5414729 (3130)	test1: 0.5305810	total: 13m 27s	remaining: 7m 33s
3300:	learn: 0.6188457	test: 0.5421430	best: 0.5421430 (3286)	test1: 0.5305810	total: 13m 55s	remaining: 7m 9s
3400:	learn: 0.6236441	test: 0.5427077	best: 0.5429899 (3391)	test1: 0.5305810	total: 14m 22s	remaining: 6m 45s
3500:	learn: 0.6271777	test: 0.5428129	best: 0.5440465 (3423)	test1: 0.5301757	total: 14m 49s	remaining: 6m 20s
3600:	learn: 0.6296906	test: 0.5439412	best: 0.5440465 (3423)	test1: 0.5297710	total: 15m 16s	remaining: 5m 56s
3700:	learn: 0.6320600	test: 0.5439412	best: 0.5445046 (3613)	test1: 0.5301757	total: 15m 43s	remaining: 5m 31s
3800:	learn: 0.6360488	test: 0.5454545	best: 0.5454545 (3799)	test1: 0.5297710	total: 16m 10s	remaining: 5m 6s
3900:	learn: 0.6385301	test: 0.5462981	best: 0.5462981 (3898)	test1: 0.5293669	total: 16m 38s	remaining: 4m 41s
4000:	learn: 0.6416258	test: 0.5477018	best: 0.5477018 (3977)	test1: 0.5293669	total: 17m 4s	remaining: 4m 15s
4100:	learn: 0.6445772	test: 0.5474213	best: 0.5485428 (4037)	test1: 0.5300838	total: 17m 32s	remaining: 3m 50s
4200:	learn: 0.6459200	test: 0.5481567	best: 0.5485428 (4037)	test1: 0.5300838	total: 17m 59s	remaining: 3m 25s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.5485427524
bestIteration = 4037

Shrink model to first 4038 iterations.
Fold  1 F-score : 0.539960
0:	learn: 0.2195627	test: 0.2195627	best: 0.2195627 (0)	test1: 0.2023919	total: 47.7ms	remaining: 3m 58s
100:	learn: 0.2775098	test: 0.2775098	best: 0.2775098 (99)	test1: 0.2516309	total: 10.2s	remaining: 8m 13s
200:	learn: 0.4130343	test: 0.4147115	best: 0.4150465 (199)	test1: 0.4145516	total: 22.9s	remaining: 9m 6s
300:	learn: 0.4678506	test: 0.4684758	best: 0.4687882 (298)	test1: 0.4528926	total: 39.8s	remaining: 10m 22s
400:	learn: 0.4918626	test: 0.4916650	best: 0.4916650 (395)	test1: 0.4730832	total: 58.9s	remaining: 11m 14s
500:	learn: 0.4996003	test: 0.4995009	best: 0.4995009 (497)	test1: 0.4796748	total: 1m 18s	remaining: 11m 41s
600:	learn: 0.5037834	test: 0.5033824	best: 0.5033824 (600)	test1: 0.4817518	total: 1m 39s	remaining: 12m 10s
700:	learn: 0.5095163	test: 0.5057563	best: 0.5057563 (700)	test1: 0.4825911	total: 1m 59s	remaining: 12m 15s
800:	learn: 0.5137325	test: 0.5078295	best: 0.5078295 (799)	test1: 0.4822006	total: 2m 22s	remaining: 12m 26s
900:	learn: 0.5170578	test: 0.5100910	best: 0.5100910 (884)	test1: 0.4846527	total: 2m 45s	remaining: 12m 31s
1000:	learn: 0.5228835	test: 0.5125370	best: 0.5128306 (989)	test1: 0.4879227	total: 3m 9s	remaining: 12m 38s
1100:	learn: 0.5284792	test: 0.5146914	best: 0.5149842 (1080)	test1: 0.4875302	total: 3m 36s	remaining: 12m 45s
1200:	learn: 0.5367089	test: 0.5168274	best: 0.5172210 (1197)	test1: 0.4871383	total: 4m 2s	remaining: 12m 47s
1300:	learn: 0.5410759	test: 0.5189550	best: 0.5189550 (1273)	test1: 0.4875702	total: 4m 30s	remaining: 12m 48s
1400:	learn: 0.5464396	test: 0.5233901	best: 0.5233901 (1396)	test1: 0.4891740	total: 4m 57s	remaining: 12m 45s
1500:	learn: 0.5507526	test: 0.5243592	best: 0.5246479 (1489)	test1: 0.4887821	total: 5m 25s	remaining: 12m 38s
1600:	learn: 0.5551492	test: 0.5249364	best: 0.5249364 (1582)	test1: 0.4896000	total: 5m 53s	remaining: 12m 30s
1700:	learn: 0.5605218	test: 0.5264804	best: 0.5264804 (1674)	test1: 0.4904153	total: 6m 21s	remaining: 12m 19s
1800:	learn: 0.5669532	test: 0.5278157	best: 0.5278157 (1792)	test1: 0.4900239	total: 6m 49s	remaining: 12m 7s
1900:	learn: 0.5712110	test: 0.5282872	best: 0.5284711 (1897)	test1: 0.4908367	total: 7m 16s	remaining: 11m 52s
2000:	learn: 0.5754986	test: 0.5301111	best: 0.5301111 (1987)	test1: 0.4908367	total: 7m 43s	remaining: 11m 34s
2100:	learn: 0.5800833	test: 0.5323993	best: 0.5323993 (2086)	test1: 0.4908367	total: 8m 9s	remaining: 11m 15s
2200:	learn: 0.5839940	test: 0.5340070	best: 0.5340070 (2200)	test1: 0.4920382	total: 8m 36s	remaining: 10m 57s
2300:	learn: 0.5885897	test: 0.5352496	best: 0.5352496 (2283)	test1: 0.4920382	total: 9m 3s	remaining: 10m 37s
2400:	learn: 0.5936210	test: 0.5353261	best: 0.5356103 (2337)	test1: 0.4920382	total: 9m 30s	remaining: 10m 17s
2500:	learn: 0.5992901	test: 0.5368503	best: 0.5368503 (2466)	test1: 0.4920382	total: 9m 57s	remaining: 9m 56s
2600:	learn: 0.6017534	test: 0.5379845	best: 0.5383721 (2546)	test1: 0.4928458	total: 10m 24s	remaining: 9m 36s
2700:	learn: 0.6068376	test: 0.5395043	best: 0.5396825 (2679)	test1: 0.4916468	total: 10m 51s	remaining: 9m 14s
2800:	learn: 0.6100501	test: 0.5405301	best: 0.5409170 (2777)	test1: 0.4916468	total: 11m 18s	remaining: 8m 52s

2900:	learn: 0.6128793	test: 0.5410946	best: 0.5411992 (2892)	test1: 0.4916468	total: 11m 45s	remaining: 8m 30s
3000:	learn: 0.6192407	test: 0.5420452	best: 0.5426087 (2962)	test1: 0.4912560	total: 12m 12s	remaining: 8m 7s
3100:	learn: 0.6221486	test: 0.5432432	best: 0.5436293 (3044)	test1: 0.4924543	total: 12m 39s	remaining: 7m 44s
3200:	learn: 0.6256881	test: 0.5438393	best: 0.5441914 (3128)	test1: 0.4912560	total: 13m 6s	remaining: 7m 21s
3300:	learn: 0.6292094	test: 0.5444015	best: 0.5444015 (3232)	test1: 0.4912560	total: 13m 33s	remaining: 6m 58s
3400:	learn: 0.6322133	test: 0.5454195	best: 0.5457000 (3384)	test1: 0.4908658	total: 13m 59s	remaining: 6m 34s
3500:	learn: 0.6349553	test: 0.5465408	best: 0.5465408 (3492)	test1: 0.4920635	total: 14m 27s	remaining: 6m 11s
3600:	learn: 0.6379342	test: 0.5471371	best: 0.5471371 (3590)	test1: 0.4920635	total: 14m 54s	remaining: 5m 47s
3700:	learn: 0.6417558	test: 0.5481510	best: 0.5481510 (3694)	test1: 0.4916733	total: 15m 21s	remaining: 5m 23s
3800:	learn: 0.6444605	test: 0.5487101	best: 0.5489894 (3789)	test1: 0.4916733	total: 15m 48s	remaining: 4m 59s
3900:	learn: 0.6467824	test: 0.5498269	best: 0.5506633 (3869)	test1: 0.4916733	total: 16m 15s	remaining: 4m 34s
4000:	learn: 0.6490975	test: 0.5501058	best: 0.5506633 (3869)	test1: 0.4920635	total: 16m 42s	remaining: 4m 10s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.550663334
bestIteration = 3869

Shrink model to first 3870 iterations.
Fold  2 F-score : 0.506294
0:	learn: 0.2069762	test: 0.2069762	best: 0.2069762 (0)	test1: 0.2520399	total: 38ms	remaining: 3m 9s
100:	learn: 0.2448502	test: 0.2448502	best: 0.2800622 (1)	test1: 0.2948135	total: 8.76s	remaining: 7m 5s
200:	learn: 0.3852459	test: 0.3852459	best: 0.3852459 (200)	test1: 0.4128596	total: 19.6s	remaining: 7m 47s
300:	learn: 0.4484045	test: 0.4490472	best: 0.4493684 (298)	test1: 0.4887097	total: 37.4s	remaining: 9m 44s
400:	learn: 0.4753765	test: 0.4731051	best: 0.4734162 (399)	test1: 0.5099285	total: 55.7s	remaining: 10m 39s
500:	learn: 0.4889068	test: 0.4852525	best: 0.4852525 (500)	test1: 0.5165354	total: 1m 15s	remaining: 11m 20s
600:	learn: 0.4961893	test: 0.4914539	best: 0.4917571 (589)	test1: 0.5200314	total: 1m 36s	remaining: 11m 43s
700:	learn: 0.5004000	test: 0.4959904	best: 0.4959904 (699)	test1: 0.5211931	total: 1m 57s	remaining: 12m 3s
800:	learn: 0.5044865	test: 0.4992000	best: 0.4992999 (787)	test1: 0.5219436	total: 2m 19s	remaining: 12m 11s
900:	learn: 0.5108242	test: 0.5031898	best: 0.5031898 (900)	test1: 0.5215348	total: 2m 40s	remaining: 12m 11s
1000:	learn: 0.5164226	test: 0.5054726	best: 0.5055732 (962)	test1: 0.5215348	total: 3m 3s	remaining: 12m 13s
1100:	learn: 0.5247836	test: 0.5077473	best: 0.5078482 (1095)	test1: 0.5250000	total: 3m 29s	remaining: 12m 21s
1200:	learn: 0.5300686	test: 0.5115910	best: 0.5116924 (1195)	test1: 0.5291829	total: 3m 57s	remaining: 12m 29s
1300:	learn: 0.5348701	test: 0.5148280	best: 0.5148280 (1299)	test1: 0.5291829	total: 4m 24s	remaining: 12m 31s
1400:	learn: 0.5417072	test: 0.5164857	best: 0.5164857 (1383)	test1: 0.5287714	total: 4m 51s	remaining: 12m 29s
1500:	learn: 0.5468992	test: 0.5178466	best: 0.5180509 (1457)	test1: 0.5310559	total: 5m 19s	remaining: 12m 23s
1600:	learn: 0.5534543	test: 0.5198030	best: 0.5198030 (1593)	test1: 0.5317829	total: 5m 45s	remaining: 12m 14s
1700:	learn: 0.5596154	test: 0.5211573	best: 0.5212598 (1663)	test1: 0.5302326	total: 6m 12s	remaining: 12m 3s
1800:	learn: 0.5638665	test: 0.5230890	best: 0.5233792 (1796)	test1: 0.5309598	total: 6m 39s	remaining: 11m 50s
1900:	learn: 0.5705557	test: 0.5245194	best: 0.5245194 (1884)	test1: 0.5305491	total: 7m 6s	remaining: 11m 35s
2000:	learn: 0.5749096	test: 0.5271196	best: 0.5271196 (1999)	test1: 0.5316847	total: 7m 33s	remaining: 11m 19s
2100:	learn: 0.5797761	test: 0.5274080	best: 0.5274080 (2055)	test1: 0.5316847	total: 8m 1s	remaining: 11m 4s
2200:	learn: 0.5832702	test: 0.5288480	best: 0.5292392 (2167)	test1: 0.5312741	total: 8m 28s	remaining: 10m 46s
2300:	learn: 0.5879245	test: 0.5306760	best: 0.5309631 (2262)	test1: 0.5304549	total: 8m 56s	remaining: 10m 29s
2400:	learn: 0.5913796	test: 0.5326829	best: 0.5326829 (2371)	test1: 0.5315871	total: 9m 23s	remaining: 10m 10s
2500:	learn: 0.5965110	test: 0.5339314	best: 0.5340355 (2484)	test1: 0.5319969	total: 9m 51s	remaining: 9m 50s
2600:	learn: 0.6014953	test: 0.5353594	best: 0.5353594 (2571)	test1: 0.5315871	total: 10m 18s	remaining: 9m 30s
2700:	learn: 0.6054054	test: 0.5362150	best: 0.5362150 (2700)	test1: 0.5315871	total: 10m 46s	remaining: 9m 9s
2800:	learn: 0.6092937	test: 0.5368892	best: 0.5371740 (2782)	test1: 0.5315871	total: 11m 13s	remaining: 8m 49s
2900:	learn: 0.6123887	test: 0.5380276	best: 0.5380276 (2871)	test1: 0.5315871	total: 11m 42s	remaining: 8m 28s
3000:	learn: 0.6167499	test: 0.5383119	best: 0.5385962 (2963)	test1: 0.5319969	total: 12m 9s	remaining: 8m 6s
3100:	learn: 0.6210837	test: 0.5389850	best: 0.5389850 (3073)	test1: 0.5331279	total: 12m 37s	remaining: 7m 43s
3200:	learn: 0.6231137	test: 0.5389850	best: 0.5395530 (3156)	test1: 0.5338462	total: 13m 6s	remaining: 7m 21s
3300:	learn: 0.6269040	test: 0.5402254	best: 0.5405090 (3270)	test1: 0.5338462	total: 13m 34s	remaining: 6m 59s
3400:	learn: 0.6294193	test: 0.5406875	best: 0.5408659 (3394)	test1: 0.5360983	total: 14m 3s	remaining: 6m 36s
3500:	learn: 0.6346715	test: 0.5411491	best: 0.5411491 (3477)	test1: 0.5345622	total: 14m 31s	remaining: 6m 13s
3600:	learn: 0.6361648	test: 0.5415373	best: 0.5418203 (3598)	test1: 0.5356869	total: 15m 1s	remaining: 5m 50s
3700:	learn: 0.6396364	test: 0.5418929	best: 0.5422808 (3671)	test1: 0.5360983	total: 15m 30s	remaining: 5m 26s
3800:	learn: 0.6428442	test: 0.5427408	best: 0.5430233 (3759)	test1: 0.5360983	total: 15m 58s	remaining: 5m 2s
3900:	learn: 0.6449275	test: 0.5435878	best: 0.5441518 (3851)	test1: 0.5360983	total: 16m 27s	remaining: 4m 38s
4000:	learn: 0.6471333	test: 0.5455601	best: 0.5455601 (3991)	test1: 0.5360983	total: 16m 55s	remaining: 4m 13s
4100:	learn: 0.6490880	test: 0.5461226	best: 0.5465094 (4084)	test1: 0.5360983	total: 17m 23s	remaining: 3m 48s
4200:	learn: 0.6507937	test: 0.5467904	best: 0.5467904 (4196)	test1: 0.5360983	total: 17m 51s	remaining: 3m 23s
4300:	learn: 0.6539500	test: 0.5462282	best: 0.5467904 (4196)	test1: 0.5356869	total: 18m 18s	remaining: 2m 58s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.5467904099
bestIteration = 4196

Shrink model to first 4197 iterations.
Fold  3 F-score : 0.532236
0:	learn: 0.2121780	test: 0.2121780	best: 0.2121780 (0)	test1: 0.1706161	total: 48.5ms	remaining: 4m 2s
100:	learn: 0.2748162	test: 0.2748162	best: 0.2748162 (100)	test1: 0.2351834	total: 7.97s	remaining: 6m 26s
200:	learn: 0.4181626	test: 0.4198312	best: 0.4211636 (197)	test1: 0.3704348	total: 21.1s	remaining: 8m 23s
300:	learn: 0.4751831	test: 0.4753965	best: 0.4753965 (299)	test1: 0.4424192	total: 41.8s	remaining: 10m 52s
400:	learn: 0.4912492	test: 0.4916583	best: 0.4920603 (390)	test1: 0.4599018	total: 1m 1s	remaining: 11m 50s
500:	learn: 0.5015974	test: 0.5009980	best: 0.5009980 (500)	test1: 0.4661777	total: 1m 21s	remaining: 12m 11s
600:	learn: 0.5069638	test: 0.5058706	best: 0.5058706 (598)	test1: 0.4691558	total: 1m 41s	remaining: 12m 25s
700:	learn: 0.5127697	test: 0.5100139	best: 0.5103093 (697)	test1: 0.4737268	total: 2m 3s	remaining: 12m 39s
800:	learn: 0.5179487	test: 0.5130538	best: 0.5130538 (800)	test1: 0.4778047	total: 2m 25s	remaining: 12m 43s
900:	learn: 0.5230043	test: 0.5155942	best: 0.5155942 (898)	test1: 0.4770346	total: 2m 48s	remaining: 12m 44s
1000:	learn: 0.5260887	test: 0.5174384	best: 0.5174384 (998)	test1: 0.4770346	total: 3m 10s	remaining: 12m 39s
1100:	learn: 0.5316654	test: 0.5191891	best: 0.5194805 (1087)	test1: 0.4766506	total: 3m 35s	remaining: 12m 44s
1200:	learn: 0.5364807	test: 0.5215170	best: 0.5216195 (1193)	test1: 0.4774920	total: 4m 3s	remaining: 12m 50s
1300:	learn: 0.5413183	test: 0.5238376	best: 0.5241271 (1296)	test1: 0.4787149	total: 4m 31s	remaining: 12m 51s
1400:	learn: 0.5453840	test: 0.5261508	best: 0.5261508 (1399)	test1: 0.4811548	total: 4m 59s	remaining: 12m 49s

1500:	learn: 0.5497777	test: 0.5277778	best: 0.5279625 (1490)	test1: 0.4811548	total: 5m 27s	remaining: 12m 43s
1600:	learn: 0.5533475	test: 0.5292163	best: 0.5295037 (1563)	test1: 0.4827586	total: 5m 55s	remaining: 12m 34s
1700:	learn: 0.5597388	test: 0.5321101	best: 0.5323966 (1696)	test1: 0.4827586	total: 6m 23s	remaining: 12m 23s
1800:	learn: 0.5648095	test: 0.5333074	best: 0.5335152 (1774)	test1: 0.4835869	total: 6m 51s	remaining: 12m 10s
1900:	learn: 0.5696299	test: 0.5346304	best: 0.5347344 (1899)	test1: 0.4848000	total: 7m 19s	remaining: 11m 55s
2000:	learn: 0.5735490	test: 0.5356934	best: 0.5358740 (1985)	test1: 0.4860112	total: 7m 47s	remaining: 11m 40s
2100:	learn: 0.5780983	test: 0.5364715	best: 0.5364715 (2090)	test1: 0.4864000	total: 8m 14s	remaining: 11m 22s
2200:	learn: 0.5810606	test: 0.5371451	best: 0.5374295 (2198)	test1: 0.4860112	total: 8m 43s	remaining: 11m 5s
2300:	learn: 0.5842782	test: 0.5386708	best: 0.5386708 (2292)	test1: 0.4860112	total: 9m 11s	remaining: 10m 46s
2400:	learn: 0.5883905	test: 0.5401942	best: 0.5401942 (2400)	test1: 0.4860112	total: 9m 39s	remaining: 10m 26s
2500:	learn: 0.5919940	test: 0.5416101	best: 0.5418929 (2494)	test1: 0.4872204	total: 10m 6s	remaining: 10m 6s
2600:	learn: 0.5954256	test: 0.5433056	best: 0.5433056 (2599)	test1: 0.4872204	total: 10m 34s	remaining: 9m 45s
2700:	learn: 0.6018294	test: 0.5441518	best: 0.5441518 (2635)	test1: 0.4848000	total: 11m 2s	remaining: 9m 23s
2800:	learn: 0.6065116	test: 0.5447862	best: 0.5448916 (2756)	test1: 0.4860112	total: 11m 29s	remaining: 9m 1s
2900:	learn: 0.6098738	test: 0.5446809	best: 0.5451731 (2831)	test1: 0.4856230	total: 11m 56s	remaining: 8m 38s
3000:	learn: 0.6124491	test: 0.5457358	best: 0.5457358 (2982)	test1: 0.4848485	total: 12m 24s	remaining: 8m 15s
3100:	learn: 0.6148724	test: 0.5459115	best: 0.5460170 (3026)	test1: 0.4864434	total: 12m 51s	remaining: 7m 52s
3200:	learn: 0.6194690	test: 0.5480881	best: 0.5480881 (3197)	test1: 0.4848485	total: 13m 19s	remaining: 7m 29s
3300:	learn: 0.6236441	test: 0.5484369	best: 0.5484369 (3299)	test1: 0.4856688	total: 13m 47s	remaining: 7m 6s
3400:	learn: 0.6276810	test: 0.5488228	best: 0.5491028 (3381)	test1: 0.4856688	total: 14m 15s	remaining: 6m 42s
3500:	learn: 0.6311940	test: 0.5497685	best: 0.5499422 (3473)	test1: 0.4884646	total: 14m 44s	remaining: 6m 18s
3600:	learn: 0.6334429	test: 0.5501543	best: 0.5501543 (3584)	test1: 0.4896661	total: 15m 12s	remaining: 5m 54s
3700:	learn: 0.6371746	test: 0.5505401	best: 0.5505401 (3661)	test1: 0.4892772	total: 15m 40s	remaining: 5m 30s
3800:	learn: 0.6400145	test: 0.5504339	best: 0.5505401 (3661)	test1: 0.4872611	total: 16m 8s	remaining: 5m 5s
3900:	learn: 0.6439572	test: 0.5510991	best: 0.5513784 (3840)	test1: 0.4884646	total: 16m 36s	remaining: 4m 40s
4000:	learn: 0.6461650	test: 0.5513784	best: 0.5513784 (3840)	test1: 0.4884646	total: 17m 3s	remaining: 4m 15s
4100:	learn: 0.6486096	test: 0.5515514	best: 0.5519368 (4075)	test1: 0.4884646	total: 17m 31s	remaining: 3m 50s
4200:	learn: 0.6517745	test: 0.5519368	best: 0.5519368 (4075)	test1: 0.4880763	total: 18m	remaining: 3m 25s
4300:	learn: 0.6552840	test: 0.5519368	best: 0.5523222 (4297)	test1: 0.4880763	total: 18m 28s	remaining: 3m
4400:	learn: 0.6567325	test: 0.5526012	best: 0.5526012 (4357)	test1: 0.4892772	total: 18m 57s	remaining: 2m 34s
4500:	learn: 0.6609381	test: 0.5530522	best: 0.5530522 (4479)	test1: 0.4888889	total: 19m 25s	remaining: 2m 9s
4600:	learn: 0.6621356	test: 0.5527735	best: 0.5530522 (4479)	test1: 0.4900872	total: 19m 55s	remaining: 1m 43s
4700:	learn: 0.6645242	test: 0.5533308	best: 0.5536092 (4639)	test1: 0.4888889	total: 20m 24s	remaining: 1m 17s
4800:	learn: 0.6654773	test: 0.5533308	best: 0.5536092 (4639)	test1: 0.4904762	total: 20m 53s	remaining: 52s
4900:	learn: 0.6678540	test: 0.5535027	best: 0.5541659 (4816)	test1: 0.4892772	total: 21m 23s	remaining: 25.9s
4999:	learn: 0.6692759	test: 0.5535027	best: 0.5541659 (4816)	test1: 0.4904762	total: 21m 52s	remaining: 0us

bestTest = 0.5541658649
bestIteration = 4816

Shrink model to first 4817 iterations.
Fold  4 F-score : 0.520626
0:	learn: 0.2213566	test: 0.2213566	best: 0.2213566 (0)	test1: 0.1947566	total: 41.1ms	remaining: 3m 25s
100:	learn: 0.2597824	test: 0.2597824	best: 0.2597824 (99)	test1: 0.2401501	total: 7.78s	remaining: 6m 17s
200:	learn: 0.3897722	test: 0.3921905	best: 0.3921905 (200)	test1: 0.3851468	total: 19.7s	remaining: 7m 49s
300:	learn: 0.4687372	test: 0.4723864	best: 0.4723864 (300)	test1: 0.4612850	total: 38.2s	remaining: 9m 57s
400:	learn: 0.4853624	test: 0.4874017	best: 0.4874017 (400)	test1: 0.4751020	total: 57s	remaining: 10m 53s
500:	learn: 0.4971955	test: 0.4981993	best: 0.4981993 (500)	test1: 0.4903226	total: 1m 16s	remaining: 11m 25s
600:	learn: 0.5030920	test: 0.5016963	best: 0.5016963 (595)	test1: 0.4911433	total: 1m 36s	remaining: 11m 45s
700:	learn: 0.5095314	test: 0.5069583	best: 0.5069583 (692)	test1: 0.4943820	total: 1m 57s	remaining: 12m 1s
800:	learn: 0.5129729	test: 0.5085284	best: 0.5088311 (764)	test1: 0.4951923	total: 2m 18s	remaining: 12m 4s
900:	learn: 0.5172754	test: 0.5116739	best: 0.5116739 (900)	test1: 0.4984026	total: 2m 39s	remaining: 12m 4s
1000:	learn: 0.5228167	test: 0.5135295	best: 0.5137325 (964)	test1: 0.4984026	total: 3m 3s	remaining: 12m 11s
1100:	learn: 0.5283389	test: 0.5147030	best: 0.5147030 (1098)	test1: 0.4996010	total: 3m 28s	remaining: 12m 19s
1200:	learn: 0.5317942	test: 0.5168539	best: 0.5168539 (1192)	test1: 0.4996010	total: 3m 55s	remaining: 12m 25s
1300:	learn: 0.5376218	test: 0.5183287	best: 0.5183287 (1300)	test1: 0.5027844	total: 4m 24s	remaining: 12m 30s
1400:	learn: 0.5424519	test: 0.5193783	best: 0.5194805 (1384)	test1: 0.5035743	total: 4m 53s	remaining: 12m 33s
1500:	learn: 0.5479187	test: 0.5201494	best: 0.5204403 (1482)	test1: 0.5059477	total: 5m 21s	remaining: 12m 29s
1600:	learn: 0.5538639	test: 0.5215001	best: 0.5216025 (1594)	test1: 0.5083135	total: 5m 49s	remaining: 12m 22s
1700:	learn: 0.5578624	test: 0.5231373	best: 0.5232399 (1695)	test1: 0.5079114	total: 6m 17s	remaining: 12m 12s
1800:	learn: 0.5650344	test: 0.5260274	best: 0.5260274 (1791)	test1: 0.5071090	total: 6m 46s	remaining: 12m 2s
1900:	learn: 0.5706118	test: 0.5279625	best: 0.5280657 (1897)	test1: 0.5071090	total: 7m 16s	remaining: 11m 51s
2000:	learn: 0.5764706	test: 0.5291935	best: 0.5294807 (1995)	test1: 0.5071090	total: 7m 45s	remaining: 11m 37s
2100:	learn: 0.5813162	test: 0.5315913	best: 0.5318776 (2087)	test1: 0.5082873	total: 8m 13s	remaining: 11m 21s
2200:	learn: 0.5857062	test: 0.5326320	best: 0.5329178 (2180)	test1: 0.5082873	total: 8m 42s	remaining: 11m 5s
2300:	learn: 0.5898496	test: 0.5343452	best: 0.5343452 (2273)	test1: 0.5082873	total: 9m 11s	remaining: 10m 47s
2400:	learn: 0.5932871	test: 0.5350962	best: 0.5350962 (2393)	test1: 0.5094637	total: 9m 40s	remaining: 10m 28s
2500:	learn: 0.5952426	test: 0.5356657	best: 0.5356657 (2498)	test1: 0.5090623	total: 10m 9s	remaining: 10m 9s
2600:	learn: 0.6011194	test: 0.5346304	best: 0.5356657 (2498)	test1: 0.5094637	total: 10m 39s	remaining: 9m 49s
2700:	learn: 0.6036892	test: 0.5372960	best: 0.5372960 (2693)	test1: 0.5094637	total: 11m 7s	remaining: 9m 28s
2800:	learn: 0.6065452	test: 0.5372960	best: 0.5382524 (2776)	test1: 0.5118110	total: 11m 36s	remaining: 9m 6s
2900:	learn: 0.6109361	test: 0.5382524	best: 0.5385362 (2895)	test1: 0.5118110	total: 12m 4s	remaining: 8m 44s
3000:	learn: 0.6140189	test: 0.5396702	best: 0.5396702 (2982)	test1: 0.5121760	total: 12m 33s	remaining: 8m 21s
3100:	learn: 0.6172293	test: 0.5393869	best: 0.5399535 (3031)	test1: 0.5121760	total: 13m 1s	remaining: 7m 58s
3200:	learn: 0.6200037	test: 0.5405196	best: 0.5408025 (3151)	test1: 0.5121760	total: 13m 30s	remaining: 7m 35s
3300:	learn: 0.6250459	test: 0.5413680	best: 0.5413680 (3270)	test1: 0.5121760	total: 13m 58s	remaining: 7m 11s
3400:	learn: 0.6260550	test: 0.5430617	best: 0.5430617 (3392)	test1: 0.5117739	total: 14m 26s	remaining: 6m 47s
3500:	learn: 0.6268109	test: 0.5430617	best: 0.5433437 (3408)	test1: 0.5117739	total: 14m 56s	remaining: 6m 23s
3600:	learn: 0.6295754	test: 0.5437307	best: 0.5442940 (3591)	test1: 0.5117739	total: 15m 24s	remaining: 5m 59s

3700:	learn: 0.6313288	test: 0.5444702	best: 0.5445755 (3609)	test1: 0.5117739	total: 15m 52s	remaining: 5m 34s
3800:	learn: 0.6335766	test: 0.5451382	best: 0.5451382 (3756)	test1: 0.5117739	total: 16m 21s	remaining: 5m 9s
3900:	learn: 0.6346890	test: 0.5453140	best: 0.5454194 (3841)	test1: 0.5117739	total: 16m 50s	remaining: 4m 44s
4000:	learn: 0.6364299	test: 0.5453140	best: 0.5457005 (3911)	test1: 0.5117739	total: 17m 18s	remaining: 4m 19s
4100:	learn: 0.6387929	test: 0.5466126	best: 0.5466126 (4076)	test1: 0.5117739	total: 17m 48s	remaining: 3m 54s
4200:	learn: 0.6406392	test: 0.5473847	best: 0.5474903 (4174)	test1: 0.5117739	total: 18m 17s	remaining: 3m 28s
4300:	learn: 0.6421186	test: 0.5474903	best: 0.5474903 (4174)	test1: 0.5121760	total: 18m 45s	remaining: 3m 2s
4400:	learn: 0.6433490	test: 0.5476650	best: 0.5476650 (4334)	test1: 0.5121760	total: 19m 15s	remaining: 2m 37s
4500:	learn: 0.6453131	test: 0.5476650	best: 0.5476650 (4334)	test1: 0.5121760	total: 19m 43s	remaining: 2m 11s
4600:	learn: 0.6465377	test: 0.5473847	best: 0.5480509 (4539)	test1: 0.5110063	total: 20m 12s	remaining: 1m 45s
4700:	learn: 0.6480043	test: 0.5477707	best: 0.5480509 (4539)	test1: 0.5121760	total: 20m 40s	remaining: 1m 18s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.5480509456
bestIteration = 4539

Shrink model to first 4540 iterations.
Fold  5 F-score : 0.518263
Full f1 score 0.523638